import { useState, useCallback, useEffect } from 'react'
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Separator } from '@/components/ui/separator'

import {
  Tooltip, TooltipContent, TooltipTrigger,
} from '@/components/ui/tooltip'
import { TooltipProvider } from '@/components/ui/tooltip'
import { formatAll } from '@/lib/citations'
import type { Citation, CitationFields } from '@/types'
import { Loader2 } from 'lucide-react'

type CitationType = Citation['type']

const FIELD_LABELS: { key: keyof CitationFields; label: string; placeholder: string }[] = [
  { key: 'author', label: 'Author(s)', placeholder: 'Last, First; Last, First' },
  { key: 'title', label: 'Title', placeholder: 'Work title' },
  { key: 'year', label: 'Year', placeholder: '2024' },
  { key: 'publisher', label: 'Publisher / Journal', placeholder: 'Publisher or journal name' },
  { key: 'journal', label: 'Journal', placeholder: 'Journal name' },
  { key: 'url', label: 'URL', placeholder: 'https://…' },
  { key: 'pages', label: 'Pages', placeholder: '1–42' },
  { key: 'volume', label: 'Volume', placeholder: '12' },
  { key: 'issue', label: 'Issue', placeholder: '3' },
]

const VISIBLE_FIELDS: Record<CitationType, Array<keyof CitationFields>> = {
  book: ['author', 'title', 'year', 'publisher', 'url'],
  article: ['author', 'title', 'year', 'journal', 'volume', 'issue', 'pages', 'url'],
  journal: ['author', 'title', 'year', 'journal', 'volume', 'issue', 'pages', 'url'],
  website: ['author', 'title', 'year', 'publisher', 'url'],
}

interface AddCitationModalProps {
  open: boolean
  documentId: string
  editCitation?: Citation
  onClose(): void
  onAdded(citation: Citation): void
  onUpdated?(citation: Citation): void
}

function PreviewBlock({ html, label }: { html: string; label: string }): JSX.Element {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
        {label}
      </span>
      {/* HTML is generated by our own formatters with escaped user input — safe to render */}
      <p
        className="text-xs leading-relaxed text-foreground"
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: html || '<span class="opacity-40">—</span>' }}
      />
    </div>
  )
}

export default function AddCitationModal({
  open,
  documentId,
  editCitation,
  onClose,
  onAdded,
  onUpdated,
}: AddCitationModalProps): JSX.Element {
  const isEditing = !!editCitation
  const [type, setType] = useState<CitationType>('book')
  const [fields, setFields] = useState<CitationFields>({})
  const [doiInput, setDoiInput] = useState('')
  const [urlInput, setUrlInput] = useState('')
  const [isbnInput, setIsbnInput] = useState('')
  const [doiLoading, setDoiLoading] = useState(false)
  const [urlLoading, setUrlLoading] = useState(false)
  const [isbnLoading, setIsbnLoading] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [isOnline, setIsOnline] = useState(navigator.onLine)

  useEffect(() => {
    if (!open) return
    if (editCitation) {
      setType(editCitation.type)
      setFields(editCitation.fields as CitationFields)
    } else {
      setType('book')
      setFields({})
    }
    setDoiInput('')
    setUrlInput('')
    setIsbnInput('')
    setError(null)
  }, [open, editCitation])

  useEffect(() => {
    const onOnline = (): void => setIsOnline(true)
    const onOffline = (): void => setIsOnline(false)
    window.addEventListener('online', onOnline)
    window.addEventListener('offline', onOffline)
    return () => {
      window.removeEventListener('online', onOnline)
      window.removeEventListener('offline', onOffline)
    }
  }, [])

  const setField = useCallback((key: keyof CitationFields, val: string) => {
    setFields((prev) => ({ ...prev, [key]: val || undefined }))
  }, [])

  const lookupDoi = useCallback(async (): Promise<void> => {
    if (!doiInput.trim()) return
    setDoiLoading(true)
    setError(null)
    try {
      const result = await window.prose.citations.fetchByDoi(doiInput.trim())
      if (result) setFields((prev) => ({ ...prev, ...result }))
      else setError('DOI not found. Check the DOI and try again.')
    } catch {
      setError('DOI lookup failed.')
    } finally {
      setDoiLoading(false)
    }
  }, [doiInput])

  const lookupIsbn = useCallback(async (): Promise<void> => {
    if (!isbnInput.trim()) return
    setIsbnLoading(true)
    setError(null)
    try {
      const result = await window.prose.citations.fetchByIsbn(isbnInput.trim())
      if (result) setFields((prev) => ({ ...prev, ...result }))
      else setError('ISBN not found. Check the number and try again.')
    } catch {
      setError('ISBN lookup failed. Make sure you are connected to the internet.')
    } finally {
      setIsbnLoading(false)
    }
  }, [isbnInput])

  const autofillUrl = useCallback(async (): Promise<void> => {
    if (!urlInput.trim()) return
    setUrlLoading(true)
    setError(null)
    try {
      const result = await window.prose.citations.fetchByUrl(urlInput.trim())
      if (result) setFields((prev) => ({ ...prev, ...result, url: urlInput.trim() }))
      else setError('Could not extract metadata from that URL.')
    } catch {
      setError('URL fetch failed.')
    } finally {
      setUrlLoading(false)
    }
  }, [urlInput])

  const handleSave = useCallback(async (): Promise<void> => {
    if (!fields.title && !fields.author) {
      setError('At minimum, provide a title or author.')
      return
    }
    setSaving(true)
    setError(null)
    try {
      const formatted = formatAll(type, fields)
      if (isEditing && editCitation) {
        const updated = await window.prose.citations.update(editCitation.id, { type, fields, formatted })
        onUpdated?.(updated as Citation)
      } else {
        const citation = await window.prose.citations.create({
          documentId,
          type,
          fields,
          formatted,
        } as Parameters<typeof window.prose.citations.create>[0])
        onAdded(citation as Citation)
      }
      onClose()
    } catch (err) {
      setError('Failed to save citation.')
      console.error('Citation save error:', err)
    } finally {
      setSaving(false)
    }
  }, [type, fields, documentId, isEditing, editCitation, onAdded, onUpdated, onClose])

  const formatted = formatAll(type, fields)
  const visibleFieldKeys = VISIBLE_FIELDS[type]

  return (
    <TooltipProvider>
    <Dialog open={open} onOpenChange={(o) => { if (!o) onClose() }}>
      <DialogContent className="flex max-h-[90vh] w-[580px] max-w-[95vw] flex-col gap-0 p-0">
        <DialogHeader className="shrink-0 border-b border-border px-5 py-4">
          <DialogTitle className="text-sm font-semibold">{isEditing ? 'Edit Citation' : 'Add Citation'}</DialogTitle>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto min-h-0">
          <div className="flex flex-col gap-5 px-5 py-4">
            {/* Type selector */}
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-medium">Type</label>
              <Select
                value={type}
                onValueChange={(v) => { setType(v as CitationType); setFields({}) }}
              >
                <SelectTrigger className="h-8 text-xs">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="book" className="text-xs">Book</SelectItem>
                  <SelectItem value="article" className="text-xs">Journal Article</SelectItem>
                  <SelectItem value="website" className="text-xs">Website</SelectItem>
                  <SelectItem value="journal" className="text-xs">Other</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Auto-fill tools */}
            <div className="flex flex-col gap-2">
              <p className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
                Auto-fill
              </p>
              <div className="flex gap-2">
                <Input
                  className="h-7 flex-1 text-xs"
                  placeholder="DOI — e.g. 10.1145/3290605"
                  value={doiInput}
                  onChange={(e) => setDoiInput(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && void lookupDoi()}
                />
                <Tooltip>
                  <TooltipTrigger asChild>
                    <span>
                      <Button
                        size="sm"
                        variant="secondary"
                        className="h-7 shrink-0 px-3 text-xs"
                        disabled={!doiInput.trim() || doiLoading || !isOnline}
                        onClick={() => void lookupDoi()}
                      >
                        {doiLoading ? <Loader2 className="h-3 w-3 animate-spin" /> : 'Look up'}
                      </Button>
                    </span>
                  </TooltipTrigger>
                  {!isOnline && (
                    <TooltipContent side="top">
                      <p className="text-xs">Internet connection required</p>
                    </TooltipContent>
                  )}
                </Tooltip>
              </div>
              <div className="flex gap-2">
                <Input
                  className="h-7 flex-1 text-xs"
                  placeholder="ISBN — e.g. 978-0-06-112008-4"
                  value={isbnInput}
                  onChange={(e) => setIsbnInput(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && void lookupIsbn()}
                />
                <Tooltip>
                  <TooltipTrigger asChild>
                    <span>
                      <Button
                        size="sm"
                        variant="secondary"
                        className="h-7 shrink-0 px-3 text-xs"
                        disabled={!isbnInput.trim() || isbnLoading || !isOnline}
                        onClick={() => void lookupIsbn()}
                      >
                        {isbnLoading ? <Loader2 className="h-3 w-3 animate-spin" /> : 'Look up'}
                      </Button>
                    </span>
                  </TooltipTrigger>
                  {!isOnline && (
                    <TooltipContent side="top">
                      <p className="text-xs">Internet connection required</p>
                    </TooltipContent>
                  )}
                </Tooltip>
              </div>
              <div className="flex gap-2">
                <Input
                  className="h-7 flex-1 text-xs"
                  placeholder="URL — https://…"
                  value={urlInput}
                  onChange={(e) => setUrlInput(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && void autofillUrl()}
                />
                <Tooltip>
                  <TooltipTrigger asChild>
                    <span>
                      <Button
                        size="sm"
                        variant="secondary"
                        className="h-7 shrink-0 px-3 text-xs"
                        disabled={!urlInput.trim() || urlLoading || !isOnline}
                        onClick={() => void autofillUrl()}
                      >
                        {urlLoading ? <Loader2 className="h-3 w-3 animate-spin" /> : 'Auto-fill'}
                      </Button>
                    </span>
                  </TooltipTrigger>
                  {!isOnline && (
                    <TooltipContent side="top">
                      <p className="text-xs">Internet connection required</p>
                    </TooltipContent>
                  )}
                </Tooltip>
              </div>
              {error && (
                <p className="text-xs font-medium text-red-500">{error}</p>
              )}
            </div>

            <Separator />

            {/* Manual fields */}
            <div className="flex flex-col gap-3">
              <p className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
                Fields
              </p>
              {FIELD_LABELS.filter((f) => visibleFieldKeys.includes(f.key)).map((f) => (
                <div key={f.key} className="flex flex-col gap-1">
                  <label className="text-xs font-medium text-muted-foreground">{f.label}</label>
                  <Input
                    className="h-7 text-xs"
                    placeholder={f.placeholder}
                    value={fields[f.key] ?? ''}
                    onChange={(e) => setField(f.key, e.target.value)}
                  />
                </div>
              ))}
            </div>

            <Separator />

            {/* Preview */}
            <div className="flex flex-col gap-3">
              <p className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
                Preview
              </p>
              <PreviewBlock html={formatted.mla} label="MLA" />
              <PreviewBlock html={formatted.apa} label="APA" />
              <PreviewBlock html={formatted.chicago} label="Chicago" />
              <PreviewBlock html={formatted.ieee} label="IEEE" />
            </div>

          </div>
        </div>

        <DialogFooter className="shrink-0 border-t border-border px-5 py-3">
          <Button variant="ghost" size="sm" className="text-xs" onClick={onClose}>
            Cancel
          </Button>
          <Button size="sm" className="text-xs" disabled={saving} onClick={() => void handleSave()}>
            {saving ? <Loader2 className="mr-1.5 h-3 w-3 animate-spin" /> : null}
            {isEditing ? 'Save changes' : 'Save citation'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
    </TooltipProvider>
  )
}
