import { useState, useEffect, useCallback } from 'react'
import type { Editor } from '@tiptap/react'
import { Button } from '@/components/ui/button'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Separator } from '@/components/ui/separator'
import { worksSection } from '@/lib/citations'
import AddCitationModal from './AddCitationModal'
import type { Citation } from '@/types'
import { Plus, Trash2, FileText } from 'lucide-react'

interface CitationPanelProps {
  documentId: string
  format: string
  editor: Editor | null
}

function CitationItem({
  citation,
  formatKey,
  onDelete,
}: {
  citation: Citation
  formatKey: keyof Citation['formatted']
  onDelete(): void
}): JSX.Element {
  return (
    <div className="group flex flex-col gap-1 rounded-md border border-border p-2.5">
      <div className="flex items-start justify-between gap-1">
        <span className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground">
          {citation.type}
        </span>
        <button
          className="opacity-0 transition-opacity group-hover:opacity-100 text-muted-foreground hover:text-destructive"
          onClick={onDelete}
          title="Delete citation"
        >
          <Trash2 className="h-3 w-3" />
        </button>
      </div>
      <p
        className="text-xs leading-relaxed text-foreground"
        // HTML generated by our own formatters with escaped user input — safe
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: citation.formatted[formatKey] || '' }}
      />
    </div>
  )
}

export default function CitationPanel({ documentId, format, editor }: CitationPanelProps): JSX.Element {
  const [citations, setCitations] = useState<Citation[]>([])
  const [addOpen, setAddOpen] = useState(false)
  const [loading, setLoading] = useState(true)

  const { heading, key: formatKey } = worksSection(format)

  useEffect(() => {
    setLoading(true)
    void window.prose.citations.getByDocument(documentId).then((result) => {
      setCitations(result as Citation[])
      setLoading(false)
    })
  }, [documentId])

  const handleAdded = useCallback((citation: Citation): void => {
    setCitations((prev) => [...prev, citation])
  }, [])

  const handleDelete = useCallback(async (id: string): Promise<void> => {
    try {
      await window.prose.citations.delete(id)
      setCitations((prev) => prev.filter((c) => c.id !== id))
    } catch (err) {
      console.error('Citation delete error:', err)
    }
  }, [])

  const insertWorksSection = useCallback((): void => {
    if (!editor || citations.length === 0) return

    const { size } = editor.state.doc

    const content = [
      { type: 'paragraph', content: [] },
      { type: 'paragraph', content: [] },
      {
        type: 'heading',
        attrs: { level: 1, textAlign: 'center' },
        content: [{ type: 'text', text: heading }],
      },
      ...citations.map((c) => ({
        type: 'paragraph',
        content: [{ type: 'text', text: stripHtml(c.formatted[formatKey]) }],
      })),
    ]

    editor.chain().focus().insertContentAt(size, content).run()
  }, [editor, citations, heading, formatKey])

  return (
    <div className="flex h-full flex-col border-l border-border">
      {/* Header */}
      <div className="flex h-10 shrink-0 items-center justify-between px-3">
        <span className="text-xs font-medium">Citations</span>
        <Button
          size="sm"
          variant="ghost"
          className="h-6 gap-1 px-2 text-xs"
          onClick={() => setAddOpen(true)}
        >
          <Plus className="h-3 w-3" />
          Add
        </Button>
      </div>

      <Separator />

      <ScrollArea className="flex-1">
        <div className="flex flex-col gap-2 p-3">
          {loading && (
            <p className="text-xs text-muted-foreground">Loading…</p>
          )}

          {!loading && citations.length === 0 && (
            <p className="text-xs text-muted-foreground">
              No citations yet. Add one to get started.
            </p>
          )}

          {citations.map((c) => (
            <CitationItem
              key={c.id}
              citation={c}
              formatKey={formatKey}
              onDelete={() => void handleDelete(c.id)}
            />
          ))}
        </div>
      </ScrollArea>

      {citations.length > 0 && (
        <>
          <Separator />
          <div className="shrink-0 p-2">
            <Button
              size="sm"
              variant="secondary"
              className="h-7 w-full gap-1.5 text-xs"
              onClick={insertWorksSection}
              disabled={!editor}
            >
              <FileText className="h-3 w-3" />
              Insert {heading}
            </Button>
          </div>
        </>
      )}

      <AddCitationModal
        open={addOpen}
        documentId={documentId}
        onClose={() => setAddOpen(false)}
        onAdded={handleAdded}
      />
    </div>
  )
}

function stripHtml(html: string): string {
  return html.replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&ldquo;/g, '“').replace(/&rdquo;/g, '”')
}
