import { useState, useEffect, useCallback } from 'react'
import type { Editor } from '@tiptap/react'
import { Button } from '@/components/ui/button'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Separator } from '@/components/ui/separator'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { toast } from 'sonner'
import { worksSection } from '@/lib/citations'
import AddCitationModal from './AddCitationModal'
import type { Citation } from '@/types'
import { Plus, Trash2, FileText, Copy, Pencil } from 'lucide-react'

interface CitationPanelProps {
  documentId: string
  format: string
  editor: Editor | null
}

const COPY_FORMATS: { key: keyof Citation['formatted']; label: string }[] = [
  { key: 'mla', label: 'MLA' },
  { key: 'apa', label: 'APA' },
  { key: 'chicago', label: 'Chicago' },
  { key: 'ieee', label: 'IEEE' },
]

function stripHtml(html: string): string {
  return html
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
}

function CitationItem({
  citation,
  formatKey,
  onEdit,
  onDelete,
}: {
  citation: Citation
  formatKey: keyof Citation['formatted']
  onEdit(): void
  onDelete(): void
}): JSX.Element {
  const [copyOpen, setCopyOpen] = useState(false)

  function handleCopy(key: keyof Citation['formatted']): void {
    void navigator.clipboard.writeText(stripHtml(citation.formatted[key]))
    toast.success(`Copied as ${COPY_FORMATS.find((f) => f.key === key)?.label}`)
    setCopyOpen(false)
  }

  return (
    <div className="group flex min-w-0 flex-col gap-1 overflow-hidden rounded-md border border-border p-2.5">
      <div className="flex items-start justify-between gap-1">
        <span className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground">
          {citation.type}
        </span>
        <div className="flex items-center gap-1 opacity-0 transition-opacity group-hover:opacity-100 has-[[data-state=open]]:opacity-100">
          <Popover open={copyOpen} onOpenChange={setCopyOpen}>
            <PopoverTrigger asChild>
              <button
                className="text-muted-foreground hover:text-foreground"
                title="Copy citation"
              >
                <Copy className="h-3 w-3" />
              </button>
            </PopoverTrigger>
            <PopoverContent className="w-32 p-1" side="bottom" align="end">
              {COPY_FORMATS.map(({ key, label }) => (
                <button
                  key={key}
                  className="w-full rounded px-3 py-1.5 text-left text-xs transition-colors hover:bg-accent"
                  onClick={() => handleCopy(key)}
                >
                  {label}
                </button>
              ))}
            </PopoverContent>
          </Popover>
          <button
            className="text-muted-foreground hover:text-foreground"
            onClick={onEdit}
            title="Edit citation"
          >
            <Pencil className="h-3 w-3" />
          </button>
          <button
            className="text-muted-foreground hover:text-destructive"
            onClick={onDelete}
            title="Delete citation"
          >
            <Trash2 className="h-3 w-3" />
          </button>
        </div>
      </div>
      <p
        className="text-xs leading-relaxed text-foreground break-all"
        // HTML generated by our own formatters with escaped user input — safe
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: citation.formatted[formatKey] || '' }}
      />
    </div>
  )
}

export default function CitationPanel({ documentId, format, editor }: CitationPanelProps): JSX.Element {
  const [citations, setCitations] = useState<Citation[]>([])
  const [addOpen, setAddOpen] = useState(false)
  const [editCitation, setEditCitation] = useState<Citation | null>(null)
  const [loading, setLoading] = useState(true)

  const { heading, key: formatKey } = worksSection(format)

  useEffect(() => {
    setLoading(true)
    void window.prose.citations.getByDocument(documentId).then((result) => {
      setCitations(result as Citation[])
      setLoading(false)
    })
  }, [documentId])

  const handleAdded = useCallback((citation: Citation): void => {
    setCitations((prev) => [...prev, citation])
  }, [])

  const handleUpdated = useCallback((citation: Citation): void => {
    setCitations((prev) => prev.map((c) => c.id === citation.id ? citation : c))
  }, [])

  const handleDelete = useCallback(async (id: string): Promise<void> => {
    try {
      await window.prose.citations.delete(id)
      setCitations((prev) => prev.filter((c) => c.id !== id))
    } catch (err) {
      console.error('Citation delete error:', err)
    }
  }, [])

  const insertWorksSection = useCallback((): void => {
    if (!editor || citations.length === 0) return

    const endPos = editor.state.doc.content.size

    const sorted = [...citations].sort((a, b) => {
      const la = firstAuthorLastName(a)
      const lb = firstAuthorLastName(b)
      return la.localeCompare(lb)
    })

    const content = [
      { type: 'pageBreak' },
      {
        type: 'paragraph',
        attrs: { role: 'works-cited-heading', textAlign: 'center', lineHeight: 2.0 },
        content: [{ type: 'text', text: heading }],
      },
      ...sorted.map((c) => ({
        type: 'paragraph',
        attrs: { role: 'citation', lineHeight: 2.0 },
        content: htmlToInlineContent(c.formatted[formatKey]),
      })),
    ]

    editor.chain().focus().insertContentAt(endPos, content).run()
  }, [editor, citations, heading, formatKey])

  return (
    <div className="flex h-full flex-col border-l border-border">
      {/* Header */}
      <div className="flex h-10 shrink-0 items-center justify-between px-3">
        <span className="text-xs font-medium">Citations</span>
        <Button
          size="sm"
          variant="ghost"
          className="h-6 gap-1 px-2 text-xs"
          onClick={() => setAddOpen(true)}
        >
          <Plus className="h-3 w-3" />
          Add
        </Button>
      </div>

      <Separator />

      <ScrollArea className="flex-1">
        <div className="flex flex-col gap-2 p-3">
          {loading && (
            <p className="text-xs text-muted-foreground">Loading…</p>
          )}

          {!loading && citations.length === 0 && (
            <p className="text-xs text-muted-foreground">
              No citations yet. Add one to get started.
            </p>
          )}

          {citations.map((c) => (
            <CitationItem
              key={c.id}
              citation={c}
              formatKey={formatKey}
              onEdit={() => setEditCitation(c)}
              onDelete={() => void handleDelete(c.id)}
            />
          ))}
        </div>
      </ScrollArea>

      {citations.length > 0 && (
        <>
          <Separator />
          <div className="shrink-0 p-2">
            <Button
              size="sm"
              variant="secondary"
              className="h-7 w-full gap-1.5 text-xs"
              onClick={insertWorksSection}
              disabled={!editor}
            >
              <FileText className="h-3 w-3" />
              Insert {heading}
            </Button>
          </div>
        </>
      )}

      <AddCitationModal
        open={addOpen}
        documentId={documentId}
        onClose={() => setAddOpen(false)}
        onAdded={handleAdded}
      />
      <AddCitationModal
        open={editCitation !== null}
        documentId={documentId}
        editCitation={editCitation ?? undefined}
        onClose={() => setEditCitation(null)}
        onAdded={handleAdded}
        onUpdated={handleUpdated}
      />
    </div>
  )
}

function decodeEntities(s: string): string {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '”')
    .replace(/&ldquo;/g, '“')
    .replace(/&rdquo;/g, '”')
}

function htmlToInlineContent(html: string): import('@tiptap/core').JSONContent[] {
  const nodes: import('@tiptap/core').JSONContent[] = []
  const parts = html.split(/(<em>.*?<\/em>)/g)
  for (const part of parts) {
    if (!part) continue
    if (part.startsWith('<em>')) {
      const text = decodeEntities(part.slice(4, -5))
      if (text) nodes.push({ type: 'text', text, marks: [{ type: 'italic' }] })
    } else {
      const text = decodeEntities(part)
      if (text) nodes.push({ type: 'text', text })
    }
  }
  return nodes.length ? nodes : [{ type: 'text', text: '' }]
}

function firstAuthorLastName(citation: Citation): string {
  const author = (citation.fields.author as string | undefined) ?? ''
  if (!author.trim()) return ''
  const firstAuthor = author.split(';')[0]!.trim()
  return firstAuthor.split(',')[0]!.trim().toLowerCase()
}
