export const DB_FILE_NAME = 'prose.db' as const
export const OLLAMA_PORT = 11434 as const
export const OLLAMA_HOST = `http://localhost:${OLLAMA_PORT}` as const
export const DEFAULT_OLLAMA_MODEL = 'llama3.2:3b' as const
export const FALLBACK_OLLAMA_MODEL = 'llama3:8b' as const
export const AUTO_SAVE_DEBOUNCE_MS = 1000 as const
export const POMODORO_DEFAULT_WORK_MINUTES = 25 as const
export const POMODORO_DEFAULT_BREAK_MINUTES = 5 as const
export const MUSIC_DEFAULT_VOLUME = 70 as const
export const EDITOR_DEFAULT_FONT_FAMILY = 'Times New Roman' as const
export const EDITOR_DEFAULT_FONT_SIZE = 12 as const
export const SIDEBAR_COLLAPSED_WIDTH = 42 as const
export const SIDEBAR_EXPANDED_WIDTH = 220 as const
export const AI_PANEL_WIDTH = 280 as const
export const MIN_WINDOW_WIDTH = 960 as const
export const MIN_WINDOW_HEIGHT = 600 as const
