import type { PresentationTheme } from '@/types/slides'

export const BUILT_IN_THEMES: PresentationTheme[] = [
  {
    id: 'prose-dark',
    name: 'Prose Dark',
    primaryColor: '#3b82f6',
    secondaryColor: '#1e3a5f',
    accentColor: '#60a5fa',
    backgroundColor: '#0f1117',
    textColor: '#e2e8f0',
    headingFontFamily: 'Inter',
    bodyFontFamily: 'Inter',
  },
  {
    id: 'academic',
    name: 'Academic',
    primaryColor: '#1e3a5f',
    secondaryColor: '#7f1d1d',
    accentColor: '#1e3a5f',
    backgroundColor: '#ffffff',
    textColor: '#1a1a2e',
    headingFontFamily: 'Georgia',
    bodyFontFamily: 'Times New Roman',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    primaryColor: '#111827',
    secondaryColor: '#6b7280',
    accentColor: '#374151',
    backgroundColor: '#ffffff',
    textColor: '#111827',
    headingFontFamily: 'Inter',
    bodyFontFamily: 'Inter',
  },
  {
    id: 'bold',
    name: 'Bold',
    primaryColor: '#f59e0b',
    secondaryColor: '#d97706',
    accentColor: '#fbbf24',
    backgroundColor: '#0a0a0a',
    textColor: '#fafafa',
    headingFontFamily: 'Inter',
    bodyFontFamily: 'Inter',
  },
  {
    id: 'soft',
    name: 'Soft',
    primaryColor: '#8b5cf6',
    secondaryColor: '#a78bfa',
    accentColor: '#c4b5fd',
    backgroundColor: '#f5f3ff',
    textColor: '#3b3756',
    headingFontFamily: 'Inter',
    bodyFontFamily: 'Inter',
  },
  {
    id: 'tech',
    name: 'Tech',
    primaryColor: '#22c55e',
    secondaryColor: '#16a34a',
    accentColor: '#4ade80',
    backgroundColor: '#0d1117',
    textColor: '#c9d1d9',
    headingFontFamily: 'Courier New',
    bodyFontFamily: 'Courier New',
  },
]
